name: blixtro-project

services:
  app:
    build: ./src
    image: blixtro
    container_name: blixtro-container
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    env_file:
      - ./src/.env
    depends_on:
      - blixtro_postgres


  blixtro_postgres:
    image: postgres:latest
    container_name: blixtro-postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: blixtro_db
      POSTGRES_USER: blixtro_user
      POSTGRES_PASSWORD: blixtro_pass
    restart: unless-stopped
    volumes:
      - blixtro_postgres_data:/var/lib/postgresql/data


volumes:
  blixtro_postgres_data:

