name: blixtro-project

services:
  # =========================
  # DJANGO APP (GUNICORN)
  # =========================
  app:
    build: ./src
    image: blixtro
    container_name: blixtro-container
    command: >
      sh -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      gunicorn config.wsgi:application
      --bind 0.0.0.0:8000
      --workers 3
      --timeout 120
      --log-level info
      --access-logfile -
      "
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    env_file:
      - ./src/.env
    environment:
      - TZ=Asia/Kolkata
    depends_on:
      - blixtro_postgres
    restart: unless-stopped

  # =========================
  # POSTGRES
  # =========================
  blixtro_postgres:
    image: postgres:latest
    container_name: blixtro-postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: blixtro_db
      POSTGRES_USER: blixtro_user
      POSTGRES_PASSWORD: blixtro_pass
    restart: unless-stopped
    volumes:
      - blixtro_postgres_data:/var/lib/postgresql/data

volumes:
  blixtro_postgres_data:
